### ISSUE TITLE
Functional Model

### ISSUE THREAD

**Issue by kslokhandwala2022** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#13]
**This is for the Final Hospital App NOT the 3 Porotype Programs**

Create a functional model **as a team**, rather than divvying up each part to individuals, for the following iteration 1

The functional model should include scenarios, epics, user story cards, initial user story conversations, use case diagrams and textual use cases, and UI mockups that are created using Adobe XD or Scene Builder. Use t-shirt sizing and then poker sizing to assign a sizing number for your user stories. Begin poker sizing with the smallest t-shirt sizes first. Storyboards are optional. However, include storyboards in your submission if you created them. **Remember to ask for feedback from the quieter members of the team by giving them time to think before asking them for their input.** 

1. using the A* algorithm, draws a path on the campus map of Hospital from a starting location (static) to a destination specified by the user. The starting and ending locations are the 30 parking spots on the map and the entrances. Do not create the paths for inside the building. You do not need to draw a path across more than one map.
2. includes a floor map editor for managing (add, edit, and delete) nodes, edges, and locations on a floor map.
3. includes two service request components. See Project Description for some possibilities.
4. create the nodes CSV file and edges CSV file for just the campus map of Brigham & Women’s Faulkner Hospital. See attached CS3733-C21 Map Data Instructions document. CSV template files are located in the Faulkner D20 Team P zip file.

- [x] Scenarios (DB)
- [x] Epics (DB)
- [x] User Stories (NOT #14)
- [x] Initial User Stories Conversation (Algo)
- [x] Use Case Diagram (UI)
- [x] Textual Use Case (Algo - UI)
- [x] UI Mockup (UI)
- [x] Poker sizing
- [ ] (Optional) storyboards

**Comment by Kohmei358** [comment]
Create a functional model **as a team**, rather than divvying up each part to individuals, for the following iteration 1

The functional model should include scenarios, epics, user story cards, initial user story conversations, use case diagrams and textual use cases, and UI mockups that are created using Adobe XD or Scene Builder. Use t-shirt sizing and then poker sizing to assign a sizing number for your user stories. Begin poker sizing with the smallest t-shirt sizes first. Storyboards are optional. However, include storyboards in your submission if you created them. **Remember to ask for feedback from the quieter members of the team by giving them time to think before asking them for their input.** 

- [ ] Scenarios
- [ ] Epics
- [ ] User Stories
- [ ] Use Case Diagram
- [ ] Textual Use Case
- [ ] UI Mockup
- [ ] Poker sizing
- [ ] (Optional) storyboards

**Comment by Kohmei358** [comment]
How should we do this? We have to do it as a whole team but I don't think everyone can participate if we do one big meeting
